import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'
import LineChart from './lineChart'

export default function Home() {
  const [labl, setLabl] = useState([])
  const [valores, setValores] = useState([])
  const [contador, setContador] = useState(0)
  const [seconds, setSeconds] = useState(0);
  const [data, setData] = useState([])
  const [datosMin, setDatosMin] = useState(0) // revisa los datos nuevos por minuto
  // mi timer
  useEffect(() => {
    const timer = setInterval(() => {
      setSeconds((prevSeconds) => prevSeconds + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const activar = async () => {
    const response = await fetch("/api/hello", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data2 = await response.json();
    const newData = data2.filter((item) => !data.some((dataItem) => dataItem.id_clientes === item.id_clientes));
    if(newData.length>0){
      if(seconds % 60 === 0){
        setDatosMin(0)
      }else{
        setDatosMin(datosMin+1)
      }
    }
    if(seconds % 60 === 0){
      setDatosMin(0)
    }
    setData([...data, ...newData]);
    setValores([...valores, data2.length])
    setLabl([...labl, contador])
    setContador(contador + 1)
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }
  }

  useEffect(() => {
    activar()
  }, [seconds])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className='flexear centrar'>Cantidad de datos en el tiempo</h1>
        <div className='grilla'>
          <div>
            <h1>Clientes</h1>
            <div className='altura'><LineChart valores={valores} etiquetas={labl} /></div>
          </div>
          <div className='flexear centrar '>
            <div className='centrar alinear2 fifty_witdh'>
              <h2 className='flexear centrar'>Datos dentro de Tabla</h2>
              <table className='all_witdh'>
                <thead className='encabezado'>
                  <tr>
                    <th>Nombre</th>
                    <th>apellido</th>
                  </tr>
                </thead>
                <tbody>
                  {data.map((item) => {
                    return (
                      <tr key={item.id_clientes}>
                        <td>{item.nombre}</td>
                        <td>{item.apellido}</td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div>
          <div>Nuevos Datos Recibidos el Ultimo Minuto: {datosMin}</div>
        </div>
      </div>
    </>
  )
}
